### ISSUE TITLE
能否增加一个排序的方式？

### ISSUE THREAD

**Issue by zhl111** [JasonGrass/auto-extension-manager#100]
比如：可以增加一个选项，把所有启动的插件按序归类，排在前端。而不是通过搜索打开或关闭某个插件
![image](https://github.com/JasonGrass/auto-extension-manager/assets/29135984/cefce3b8-16a4-49b5-ba53-9bcc27017ce0)

---

Extension Manager 0.5.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
https://github.com/JasonGrass/auto-extension-manager/releases/tag/v0.5.9
