### ISSUE TITLE
Suggestion: allow to pin and unpin extension

### ISSUE THREAD

**Issue by aspiers** [JasonGrass/auto-extension-manager#103]
Hello and thank you very much for this great extension!  Sorry for posting in English but I do not know Chinese so I will have to use Google Translate.

It would be really helpful if there was a feature for pinning and unpinning extensions to the toolbar.  Currently it is awkward to do this with the native menus when a large number of extensions are installed.

您好，非常感谢您提供这个出色的扩展！ 抱歉用英文发帖，但我不懂中文，所以我必须使用谷歌翻译。

如果有一个用于固定和取消固定工具栏扩展的功能，那将会非常有帮助。 目前，当安装了大量扩展时，使用本机菜单执行此操作很尴尬：

![image](https://github.com/JasonGrass/auto-extension-manager/assets/100738/6c812e63-ae19-4f77-a8f0-7cc788947d02)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/100738/90927178-787e-4dba-8404-f87c6f7f7e8a)

**Comment by JasonGrass** [comment]
Thank you for your support for this extension, but unfortunately, Chrome does not provide a pin-related API, so this feature cannot be implemented. 
I guess Chrome is to prevent extensions from secretly pinning themselves to the toolbar.

[chrome.management  |  API  |  Chrome for Developers](https://developer.chrome.com/docs/extensions/reference/api/management )

**Comment by aspiers** [comment]
Ah I see, that's a shame :-( Thanks a lot for the quick reply!

**Comment by Nikhilsinha666** [comment]
Oh, I was just about to request this same feature, and I came here to make this feature request. I found this issue at the top; I don&#39;t know how the algorithm read my mind.
