### ISSUE TITLE
分组变更时刷新排序

### ISSUE THREAD

**Issue by Brbrbr1995** [JasonGrass/auto-extension-manager#104]
当前需要重新打卡才会排序
另外希望可以添加选项不要把已关闭扩展置底

**Comment by JasonGrass** [comment]
> 当前需要重新打卡才会排序

通常来说，分组变更等相关的设置是个低频操作，而且在设置页面可以直接看到分组结果，没有太大的必要实时更新到正在打开的 popup 上

---

> 另外希望可以添加选项不要把已关闭扩展置底

0.5.10 版本添加了一个选项，分组显示时，可以设置默认排序按名称排序，扩展的启用与禁用就不会影响排序了
