### ISSUE TITLE
建议: 删除按钮可以设置是否显示

### ISSUE THREAD

**Issue by Wirili** [JasonGrass/auto-extension-manager#106]
1、删除按钮可以设置是否显示，怕不小心点到，有些扩展配置比较多，重新安装比较麻烦。
2、禁用扩展，左上角那个数量不会实时刷新。
3、希望弹窗的高度能够自适应，插件少的话，下面一大片空白位置。
---

Extension Manager 0.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

**Comment by JasonGrass** [comment]
删除这个，浏览器会做二次确认的，不会出现点到了就直接删除的情况
