### ISSUE TITLE
建议增加小眼睛开关

### ISSUE THREAD

**Issue by iseeyo** [JasonGrass/auto-extension-manager#107]
建议增加小眼睛开关，点击小眼睛“扩展图标在工具栏显示或者隐藏”，但是应用本身并不关闭！

**Comment by JasonGrass** [comment]
是指 Pin 这个功能吗？

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/d21122d3-412a-41fd-afbc-a00caab29646)

Pin 这个功能，浏览器没有提供 API

**Comment by iseeyo** [comment]
> 是指 Pin 这个功能吗？
> 
> ![image](https://private-user-images.githubusercontent.com/10756994/296554220-d21122d3-412a-41fd-afbc-a00caab29646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDEwMzAsIm5iZiI6MTcwNTI0MDczMCwicGF0aCI6Ii8xMDc1Njk5NC8yOTY1NTQyMjAtZDIxMTIyZDMtNDEyYS00MWZkLWFmYmMtYTAwY2FhYjI5NjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDEzNTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYzdjZDJkNDI4YTcyODdkNGUzOGQ4NDI4MjdlYzQ0N2FmZTMwMzQyMjRkNjY4NDE1NDQ4ZjExYjFkNzI0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.47Ft0V9XoSRRbpJvMfeCvTDmoXBEb7uvrv_n2b-y-Fc)
> 
> Pin 这个功能，浏览器没有提供 API

对，edge上是小眼睛图标，没有API可惜了
![1705240716844](https://github.com/JasonGrass/auto-extension-manager/assets/7778828/1b223adf-3edf-49b4-82ef-4da6cb75be16)
