### ISSUE TITLE
当一个扩展有两条规则时似乎有条件判断bug

### ISSUE THREAD

**Issue by KCCat** [JasonGrass/auto-extension-manager#108]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/24634997/2edc7ade-5f00-433e-9847-30f93763a475)

如图,动作都是自定义(任意tab匹配时打开,tab都不匹配时关闭)
这样设置后,我在触发第2条规则,但是没有触发第3条规则的情况下,切换tab蓝色图标的扩展会随着tab切换一开一关

---

Extension Manager 0.5.12
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
这里逻辑上有冲突，没有想到啥好的解决办法，也可以帮忙想想 😂

原因是这样，
比如现在一个标签打开了  bilibili.com/video ，但是没有任何标签打开 live.bilibili.com 
所以，规则 1 满足，会打开扩展
规则2 不满足，会关闭扩展

这里就会有冲突，最终结果就看执行顺序了

---

建议针对特定的扩展，单独给它建一条规则，多个规则的目标扩展不要重叠。

**Comment by JasonGrass** [comment]
问题就是  **当一个扩展在两条规则中时**   

如果这两条规则给出的结果不一样，不知道听谁的

**Comment by KCCat** [comment]
我想是不是可以维护一个字典,key是扩展名称,value是2位长度的二进制值.
每次执行完一条规则之后把各个扩展的开关结果与字典值计算或,那么各个值表示的含义可以是:
 `0b01` 表示开
 `0b00` 表示关
 `0b10` 表示有规则强制该扩展为关
而 `0b11` 就可以表示有规则计算结果是开但有规则强制该扩展为关.
当所有规则跑完之后处理扩展的开关
