### ISSUE TITLE
第一次打开部分网站，不能自动启用插件

### ISSUE THREAD

**Issue by carldats** [JasonGrass/auto-extension-manager#109]
第一次打开网站，没有启用РуТрекер插件，等到网站连接超时后才自动启用插件，这时候刷新页面才能访问

![image](https://github.com/JasonGrass/auto-extension-manager/assets/25075365/057ef67a-6b14-466b-aeea-1b93a56650d6)

---

Extension Manager 0.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
应该是要等待网站加载完成

**Comment by JasonGrass** [comment]
看样子不太行，当前使用的 API 是这个：
https://developer.chrome.com/docs/extensions/reference/api/tabs#event-onUpdated

onUpdated，文档没有详细描述触发时机，不过看起来是等待页面刷新完成之后触发的。

如果需要像油猴那样，可以跟踪页面加载的具体时机，需要额外的权限，而且这个权限比较敏感，对于这个扩展管理工具来说，是不必要的。

油猴扩展的权限：
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/1552bb7c-edd4-431b-8fcf-795687b61e7b)

扩展管理器的权限：
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/49a25095-e753-40fd-b075-88f77eead41d)
