### ISSUE TITLE
Add a shortcut to the the link of the extension's page

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#110]
I really like using your tool to search for an extension quickly and then turn it on/off or go to the settings of the extension. It would be great if you can add a Pin to toolbar option as well:

![image](https://github.com/JasonGrass/auto-extension-manager/assets/18227319/a4d9e5be-abaf-4819-abc7-db67beb98778)

**Comment by JasonGrass** [comment]
same as #103

**Comment by chaoscreater** [comment]
Would it be possible to add a shortcut to the the link of the extension's page?

For example:

`chrome://extensions/?id=hhlhjgianpocpoppaiihmlpgcoehlhio`

From there, users can choose the option to pin to toolbar.

![image](https://github.com/JasonGrass/auto-extension-manager/assets/18227319/d8420002-aa04-4e70-991a-95a0225a4229)

Basically, we just need to know the extension ID for each extension and then provide the above URL to the page.
