### ISSUE TITLE
我打开分组多选后，插件弹窗显示一片空白

### ISSUE THREAD

**Issue by zhl111** [JasonGrass/auto-extension-manager#111]
关闭即正常显示，不知是什么原因

**Comment by JasonGrass** [comment]
必现吗？帮忙看下是否有异常输出。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/5c73a783-ed2f-4651-b5a4-456ed7bfbd2d)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/fc035bf6-a0c7-4b67-ab0c-afc2e9df6b2d)

**Comment by JasonGrass** [comment]
哦，我发现一个问题，非开发模式，popup 页面的控制台无法打开~ 😶

**Comment by JasonGrass** [comment]
嗯，现在的问题是，在这个 popup 页面，打不开调试控制台，不知道发生了什么。 😥

**Comment by JasonGrass** [comment]
问题还会出现吗？更新扩展到 0.5.14 版本之后，如果还是出现问题，可以在 Popup 中通过右键菜单看看控制台输出。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/fab62597-4b06-4da2-8029-3e6fe80cc723)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/8c38995b-2ed8-45e1-b6e1-6c4f18ce0e37)

**Comment by JasonGrass** [comment]
是多选处理的 BUG ，暂时需要你把多选功能关掉。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/0ee2ae8e-1587-4d7a-a796-7ff054d42ea4)

原因是被选中的分组，被删除了，下一次打开 popup 就出了问题。

**Comment by JasonGrass** [comment]
还有一个办法，是删除本地保存的 activeGroups 数据。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/ccd5e85f-cca0-41f8-9a0c-d1a322eac14b)
