### ISSUE TITLE
Show URL in History section

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#113]
Hi there,

Is it possible to include the URL in the History section? This will be useful for troubleshooting purposes. I was having issues trying to figure out what URL kept disabling and enabling my extension "Open in Firefox":

![image](https://github.com/JasonGrass/auto-extension-manager/assets/18227319/635681e1-0f6c-40f8-b7c8-eccc1a66ddc0)

I know exactly what rule is causing this, but because the rule is quite complex and uses regex for the URL, it's not very clear why it was behaving like this. It wasn't working the way I wanted.

I did manage to fix my issue, but it would have been so much easier if I can look at the exact URL. Sometimes when you login to e.g. https://teams.microsoft.com, it will redirect you to the Microsoft login page at https://login.microsoftonline.com/..... and this URL can have a different query string or hash. For example:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=5e3ce6c0-2b1f-4285-8d4b-75ee7xxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fteams.microsoft.com%2Fgo&state=eyJpZCI6ImViZWY0xxxxxxxxxxxxxxxDVhZC1iMzgxLTliNTg3NDQ2ZWZhNyIsInRzIjoxNzA3NzcyMjU3LCJtZXRxxxxxxxxxxxxxxxxxxxxxxaW9uIn0%3D&nonce=1233c957-a0d6-46e8-bfbf-d97f1df76f5f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.4&client-request-id=c76eccccccccccccccc7c-6b28ebbbbbbb7&response_mode=fragment

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=5e3ce6c0-2b1f-4285-8d4b-75ee78787346&redirect_uri=https%3A%2F%2Fteams.microsoft.com%2Fgo&state=zzzzzzzzzzzzzzzzY0YTQ1LTk4ZWItNDVhZC1iMzgxLTliNTg3NDQ2ZxxxxxxxxxxxxxxxzIjoxNzA3NxxxxxxxxxcmVjdEludGVyYWN0aW9uIn0%3D&nonce=1233c957-a0d6-46e8-bfbf-d97f1df76f5f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.4&client-request-id=c76e41yyyyyyyyyyyyyy-a27c-6b28e4zzzzzzzzzz47&response_mode=fragment

As you can see, the URLs are different, and depending on your regex pattern, it may or may not match properly. I didn't know what the URL was, I had to find it out through another method. It would be awesome if I can see this in the history.

**Comment by JasonGrass** [comment]
added at 0.5.14

**Comment by chaoscreater** [comment]
@JasonGrass 

I think this broke the History tab. I'm not seeing anymore history for the triggered rules.
