### ISSUE TITLE
Question regarding rules

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#114]
Say if I have 2 rules.

Rule A:
- https://www.google.com
- https://microsoft.com
The rule is set to Disable only when matched. This means it will enable itself when the rule doesn't match

Rule B:
- https://yahoo.com
The rule is set to Disable only when matched. This means it will enable itself when the rule doesn't match

Both rule will disable the Chrome extension named ABC.

Now, say if I browse to https://yahoo.com. Rule B should disable extension ABC, but rule A enables the extension ABC because yahoo.com is not found in either of the 2 URLs. However, I don't really want this behaviour.

If I go to yahoo.com, I expect the extension ABC to be disabled. If I leave yahoo.com, I expect the extension ABC to be enabled. I want this to only be done by the rule that is related to yahoo.com. No other rules should be interfering with disabling/enabling the extension. In other words, I want to have an isolated/sandboxed rule. Rule B should be active when yahoo.com is matched and if Rule B is active, all other rules should not kick in, until I have browsed AWAY from yahoo.com.

Perhaps there's a way to disable/enable rules based on conditions?

**Comment by JasonGrass** [comment]
For your current issue, consider using custom settings to disable the automatic enabling or disabling of extensions
this may be helpful.

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/9900a258-730b-41fe-a63b-fd23dc7af2cc)

**Comment by chaoscreater** [comment]
Thanks, I'm using that already. However, I don't want to manually reload the page in order to enable/disable the target extension(s). If there's a way to toggle rules on/off based on the conditions of other rules, that would be great.

**Comment by JasonGrass** [comment]
> 
> This is an issue of conflicting rules, and I am contemplating a solution. The current idea is that if an extension appears in multiple rules, the priority of the rules should be set according to the match situation, and only the rule with the higher priority should be executed. For example, when opening yahoo.com, since Rule B explicitly mentions yahoo.com and Rule A does not, Rule B has a higher priority. Therefore, for the extension ABC, only Rule B is executed and Rule A is ignored.

In version 0.5.13, the issue has been fixed according to the above-mentioned idea.
