### ISSUE TITLE
规则匹配的条件可否设置为书签？

### ISSUE THREAD

**Issue by StrollStars** [JasonGrass/auto-extension-manager#115]
之所以提这个，是因为书签不全是URL，有些是执行脚本，就是网上一些把JS代码收藏成书签的那种。
目前想实现的是，在当前页面点击了书签后，能够自动开启指定的扩展。

**Comment by JasonGrass** [comment]
实现不了，因为需要调用浏览器扩展管理相关的 API，这些 API 只能在浏览器扩展中才能使用。

曲线救国的办法可能也有，那就过于复杂了。

对于你的问题，你可以尝试置顶功能（在规则配置的动作配置中）。在打开特定网站时，将一部分扩展置顶显示，然后手动决定打开或关闭扩展。

**Comment by StrollStars** [comment]
@JasonGrass 谢谢这个方案，我试试。
