### ISSUE TITLE
Feature Request - re-order the URLs

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#116]
I currently have a lot of rules with a lot of URLs in each rule. In order to make it more organized and manageable, I group the URLs that are similar (in domain) together. For example, it might look something like this:

```
(?:https?:\/\/)?outlook\.office365\.com$
(?:https?:\/\/)?outlook\.office365\.com\/mail$
(?:https?:\/\/)?outlook\.office\.com$
(?:https?:\/\/)?outlook\.office\.com\/mail$
(?:https?:\/\/)?portal\.azure\.com\/.*$
(?:https?:\/\/)?teams\.microsoft\.com\/_#\/activity$
```

The problem is, if in the future I need to add a new URL for Office365, I can't easily put it in the proper order. Let's say I want to add this:
`(?:https?:\/\/)?outlook\.office365\.com\/mail\/inbox.*`

then ideally, it should be added here:

```
(?:https?:\/\/)?outlook\.office365\.com$
(?:https?:\/\/)?outlook\.office365\.com\/mail$
(?:https?:\/\/)?outlook\.office365\.com\/mail\/inbox.*   <-----------------
(?:https?:\/\/)?outlook\.office\.com$
(?:https?:\/\/)?outlook\.office\.com\/mail$
(?:https?:\/\/)?portal\.azure\.com\/.*$
(?:https?:\/\/)?teams\.microsoft\.com\/_#\/activity$
```

but I can't do that easily. If there's a button that allows you to drag the rules up or down, that would be great.

**Comment by JasonGrass** [comment]
added at 0.5.14
