### ISSUE TITLE
希望可以增加  置顶固定显示的 按钮

### ISSUE THREAD

**Issue by leeaikong** [JasonGrass/auto-extension-manager#118]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/40814658/71c92407-5480-4ce3-aa62-9e8942ea35dc)

图片中红点部分 添加 图钉按钮 （置顶固定显示）
图片中绿点部分 添加   管理扩展程序  按钮 （点击进入 扩展管理界面chrome://extensions/）

**Comment by JasonGrass** [comment]
`添加 管理扩展程序 按钮`
这个提议与 #110   中的相同，此 issue 先关闭
