### ISSUE TITLE
some issue & proposal

### ISSUE THREAD

**Issue by KamiyaMinoru** [JasonGrass/auto-extension-manager#120]
1. 是否可以增加「排序」或「自由更名」
2. 有可能增加「將extension在工具列放置/移除」嗎?
3. 黑暗模式有點問題(disable app) (跟Windows 7的黑暗模式看起來有衝突)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/78710607/1055d3b0-c52f-47ff-996b-f631e014d321)

---

Extension Manager 0.5.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.140

**Comment by JasonGrass** [comment]
1 是否可以增加「排序」或「自由更名」

自由排序暂时没有时间开发，可以在这里设置其它排序选项

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/aebd25e2-b6e9-4c0d-9637-a91e7ab020ba)

扩展管理  中可以设备别名

2 有可能增加「將extension在工具列放置/移除」嗎?

same as #118 

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/918b2024-d6fc-423a-8d56-c0ad0de64187)


3 黑暗模式有點問題(disable app) (跟Windows 7的黑暗模式看起來有衝突)

没看懂，具体问题在哪里？冲突是指哪两件事情的冲突？你的预期是什么样子，实际是什么样子？

**Comment by KamiyaMinoru** [comment]
感謝回應

我的截圖中可以看到
黑暗模式下
關閉的套件
是背景和文字變灰
而不是只有文字變灰
不曉得這樣是不是正常的
但我覺得怪怪的
因為背景變色通常是onhover的反應?

**Comment by JasonGrass** [comment]
这里是设计如此，亮色模式下，启用与禁用的扩展，背景颜色也不一样。目的是更明显地区分扩展是否启用。

不过，这里的 UI 设计确实算不上漂亮，UI 美化不是我擅长的领域。😭
