### ISSUE TITLE
即时搜索提示失效

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#121]
Version
0.5.15
老版本输入提示正常，新版本明明按顺序输入名称字符，根本不提示或者被过滤掉了，搜索不到插件。请大佬修复，谢谢！

另外一个问题就是弹出界面明显有2-3秒延迟。

**Comment by JasonGrass** [comment]
我试了下，搜索好像没有啥问题，麻烦帮忙录个屏，然后看下控制台有没有什么错误输出

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/ab40f95b-be11-4e7a-9e92-af92d8fe1173)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/e8d4837c-9063-402c-8969-c26d04e2ac77)

**Comment by JasonGrass** [comment]
可能是另一个问题引起的 🤣 搜索框的布局有点问题，挡住了搜索结果，正在修复 

你切换到网格显示模式试试看能不能搜到
