### ISSUE TITLE
可以支持快速将扩展固定在扩展栏的功能么

### ISSUE THREAD

**Issue by zcr268** [JasonGrass/auto-extension-manager#131]
RT ,可以快速固定到扩展栏,或者可以打开chrome 对应插件的管理页面哪里可以打开固定按钮.
使用场景主要是一些不常用扩展或者新安装的扩展很难找到并固定到扩展栏

**Comment by JasonGrass** [comment]
same as #103

**Comment by zcr268** [comment]
可以打开扩展对应的权限管理页面也行的.里面有对应的按钮就会方便很多了.总比各种找不到要好.
![image](https://github.com/JasonGrass/auto-extension-manager/assets/9443858/c13577ee-7767-496a-ba6c-e90f6a61a10e)
