### ISSUE TITLE
两个小建议…

### ISSUE THREAD

**Issue by Itzamana** [JasonGrass/auto-extension-manager#135]
一是可否给popup页面添加一个显示历史记录的标签或按钮，点击后就可以在popup里查看历史记录，这样就不用每次都进到扩展设置页面里看了，就更方便了…

二是关于规则设置里的url链接匹配，可否添加一个开关，只要url匹配成功，那么这个url匹配成功的网页没有关闭的情况下，切换到其他标签也不会触发“匹配才关闭/匹配才打开”这样…
现在的情况是…我设置好url匹配+匹配才开启，然后我打开网页url匹配成功，扩展自动开启，但我切换到其他标签浏览网页的时候，扩展会自动关闭…
如果有个开关，当开关开启时，就算我切到其他标签，扩展也不会自动关闭，除非我关掉了url匹配成功的那个网页…

**Comment by JasonGrass** [comment]
查看历史纪录应该不是一个高频场景吧  🤣

第二个问题，你应该是用自定义配置

<img width="885" alt="image" src="https://github.com/JasonGrass/auto-extension-manager/assets/10756994/f9b17980-f878-4e5f-92e5-00fe4fb37b17">

**Comment by Itzamana** [comment]
哈哈哈哈感谢回复，原来是在这里……历史记录那个主要是想知道哪些扩展自动更新了，毕竟chrome是一点提示都没有…
