### ISSUE TITLE
“启用扩展之后，刷新当前页面”选项不刷新后台打开的标签页

### ISSUE THREAD

**Issue by Franinc** [JasonGrass/auto-extension-manager#137]
如题，启用选项“启用扩展之后，刷新当前页面”后，如果很快切到激活扩展的后台页是能正常自动刷新，但如果几分钟后才切过去就不会刷新。（个人习惯后台开新页，处理完当前页再处理后台页，所以后台页会等很久）

例子：规则如下图，从twitter后台打开某画师p站链接，此时日志显示Powerful Pixiv Downloader扩展从禁用变启用，但几分钟后切去后台的p站标签页会发现网页没自动刷新，扩展也没在此网页加载（此时扩展仍启用中），手动刷新后正常加载。
如果后台打开p站链接并在短时间内切到后台p站标签页就正常自动刷新。此扩展一方面自动启用后需刷新才加载，另一方面在网页添加按钮也修改预览图大小，很容易分辨扩展是否加载了。

![Snipaste_2024-04-16_19-36-02](https://github.com/JasonGrass/auto-extension-manager/assets/26399054/76a21d84-355c-47d4-99ce-5d9f4f2a494b)

---

Extension Manager 0.5.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
现在确实有这个问题，当前只会刷新当前打开的页面（也就是打开 Pixiv 之后，需要直接切换到新打开的标签页），不会刷新后台打开的页面。

**Comment by JasonGrass** [comment]
问题在 0.5.21 版本处理，可以升级后看看
