### ISSUE TITLE
强制关闭我的另一个新标签插件：infinity pro

### ISSUE THREAD

**Issue by leoyang91** [JasonGrass/auto-extension-manager#145]
我把新标签页插件infinity固定了  但是会强制把它关闭  导致我的新标签页用不了

---

Extension Manager 0.5.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by leoyang91** [comment]
可能是因为我固定了infinity，同时在规则里加入了infinity导致的。这个问题不可复现了

**Comment by JasonGrass** [comment]
固定分组中的扩展，在 Popup 中手动切换分组时，不会被禁用。通常将常驻的扩展放在此分组中。
注意：如果在规则配置中，明确配置关闭某个扩展，即使此扩展在固定分组中，禁用依旧有效。
