### ISSUE TITLE
关于正则引擎

### ISSUE THREAD

**Issue by StrollStars** [JasonGrass/auto-extension-manager#155]
请问，规则设置匹配条件用正则表达式时，我该用[regex101](https://regex101.com/)8个中的哪个进行测试？

**Comment by JasonGrass** [comment]
![image](https://github.com/user-attachments/assets/61e09997-5795-481c-bfac-40f30f363abf)

就直接这样写啊

**Comment by JasonGrass** [comment]
或者你用这个网站测试

[正则表达式测试工具 - 在线工具](https://tool.lu/regex/ )

**Comment by StrollStars** [comment]
谢谢开发者分享。
