### ISSUE TITLE
建议新增功能点，启用的插件右键增加小眼睛

### ISSUE THREAD

**Issue by sqcsl-dev** [JasonGrass/auto-extension-manager#156]
如图所示，这里我以油猴为例，点击右键后，增加是否在工具栏显示的小眼睛，建议默认开启是不要显示在工具栏。
![image](https://github.com/user-attachments/assets/3d65326b-42ff-48f0-9584-66dcd17a138d)
![image](https://github.com/user-attachments/assets/4930a778-f6d8-4a13-9ce7-7942501591f3)

**Comment by JasonGrass** [comment]
[Suggestion: allow to pin and unpin extension · Issue #103 · JasonGrass/auto-extension-manager](https://github.com/JasonGrass/auto-extension-manager/issues/103 )  

没有相关的 API，无法实现
