### ISSUE TITLE
允許全行點 Allow clicking on the whole line

### ISSUE THREAD

**Issue by jidanni** [JasonGrass/auto-extension-manager#157]
建議： Currently to enable an item, we can only click in this certain area (A).
![M](https://github.com/user-attachments/assets/65b4152c-16d8-456d-802d-b64138cd486a)
Why not allow clicking anywhere on the entire line?
The idea is making it easier to click.

**Comment by JasonGrass** [comment]
最新版本 0.5.20 已支持
