### ISSUE TITLE
建议点击关闭的时候,扩展不要直接移动到最后

### ISSUE THREAD

**Issue by YJL12345** [JasonGrass/auto-extension-manager#163]
建议点击关闭的时候,扩展不要直接移动到最后,因为这会让人失去焦点,回头找很麻烦,其他管理都是把扩展留在原位置的

**Comment by JasonGrass** [comment]
可以将排序方式设置成按名称排序，这样禁用扩展的时候，就不会刷新排序了

![image](https://github.com/user-attachments/assets/cf939649-d0ef-45f7-9131-c30a0a74a476)

**Comment by JasonGrass** [comment]
0.5.24 版本，将默认排序方式设置成了扩展名称排序
