### ISSUE TITLE
建议：添加“一键关闭所有扩展”的功能

### ISSUE THREAD

**Issue by JerryYang-30** [JasonGrass/auto-extension-manager#174]
![image](https://github.com/user-attachments/assets/3c1fcae8-08d5-48a1-93b2-0866e38f6113)

有些场景下，需要关闭所有扩展。如上图，SimpleExtManager有一个“全启用/全禁用”的按钮，可以一键关闭所有扩展（除了扩展管理器本身）。

我原本是想利用本扩展的“情景模式 + 规则设置” 来实现“全禁用”的功能，匹配后关闭 所有扩展。但是这样需要在“规则执行目标：扩展（组）”里手动添加所有扩展，不能实现动态更新。（如下图）

![image](https://github.com/user-attachments/assets/f14578fe-91b7-410d-8cb3-e638c3d3dd8d)

**Comment by JasonGrass** [comment]
https://github.com/JasonGrass/auto-extension-manager/releases/tag/v0.5.25
