### ISSUE TITLE
这个分组不能切换插件的状态吗？

### ISSUE THREAD

**Issue by kickTiger** [JasonGrass/auto-extension-manager#18]
这个插件不是按照分组切换不同的插件吗？

这个分组只是纯粹的筛选了好看，而不是切换插件？

能够点击了就切换到另外一组插件吗？

**Comment by JasonGrass** [comment]
暂时没有这个功能，目前分组有两个功能：
1 筛选了好看
2 设置插件的自动开关规则时，可以按分组指定

我的想法是，扩展的开启或关闭，通过规则来自动实现。
所以这里做个需求调研，想了解一下你这里的具体使用场景，什么情况下，会想要手动打开或关闭一组扩展。

根据使用场景，后面可以考虑优化。

**Comment by Whichbfj28** [comment]
手动打开或关闭一组扩展 会比较付符合正常逻辑

**Comment by kickTiger** [comment]
> @kickTiger 暂时没有这个功能，目前分组有两个功能： 1 筛选了好看 2 设置插件的自动开关规则时，可以按分组指定
> 
> 我的想法是，扩展的开启或关闭，通过规则来自动实现。 所以这里做个需求调研，想了解一下你这里的具体使用场景，什么情况下，会想要手动打开或关闭一组扩展。
> 
> 根据使用场景，后面可以考虑优化。

### 使用场景
1. 这么说吧，使用最多的就是按组切换不同的插件。
2. 按照规则切换反而是小概率使用的功能，需要但不是经常用。
3. 不可能为那么多网站都写规则去切换的，重复写太麻烦，然后规则太多话会很卡。
4. 所以两者融合是最佳的方案 ，既可以手动切换，也可以按规则切换。

**具体功能可以参考这个插件** https://microsoftedge.microsoft.com/addons/detail/%E6%89%A9%E5%B1%95%E7%AE%A1%E7%90%86%E5%99%A8%EF%BC%88extension-manager%EF%BC%89/bhahgfgngfghgjhnpplmemebhenieijb
他的插件管理和分组，还有固定功能，已经是非常完美了。唯一的问题就是 按规则切换的限制了数量。
但是作者你的插件不限制规则的数量。所以目前我是两者并存的使用。

如果你能把他的分组这些功能完美的融合进来，就可以完全替换这个插件了。

**Comment by JasonGrass** [comment]
> > @kickTiger 暂时没有这个功能，目前分组有两个功能： 1 筛选了好看 2 设置插件的自动开关规则时，可以按分组指定
> > 我的想法是，扩展的开启或关闭，通过规则来自动实现。 所以这里做个需求调研，想了解一下你这里的具体使用场景，什么情况下，会想要手动打开或关闭一组扩展。
> > 根据使用场景，后面可以考虑优化。
> 
> ### 使用场景
> 1. 这么说吧，使用最多的就是按组切换不同的插件。
> 2. 按照规则切换反而是小概率使用的功能，需要但不是经常用。
> 3. 不可能为那么多网站都写规则去切换的，重复写太麻烦，然后规则太多话会很卡。
> 4. 所以两者融合是最佳的方案 ，既可以手动切换，也可以按规则切换。
> 
> **具体功能可以参考这个插件** https://microsoftedge.microsoft.com/addons/detail/%E6%89%A9%E5%B1%95%E7%AE%A1%E7%90%86%E5%99%A8%EF%BC%88extension-manager%EF%BC%89/bhahgfgngfghgjhnpplmemebhenieijb 他的插件管理和分组，还有固定功能，已经是非常完美了。唯一的问题就是 按规则切换的限制了数量。 但是作者你的插件不限制规则的数量。所以目前我是两者并存的使用。
> 
> 如果你能把他的分组这些功能完美的融合进来，就可以完全替换这个插件了。

明白了，我最近加上~

**Comment by gbsix** [comment]
扩展管理就是扩展太多的时候才会用到，应该像extension manger那样，点击分组就自动切换到此分组并同时保留固定的扩展， 会比较付符合正常逻辑。添加规则的确是少部分网站才会用到。 看到新版本已经做了调整，非常好！

**Comment by kickTiger** [comment]
辛苦作者了，非常感谢功能的增加。


这里有一点小小的问题，提出来探讨下。
在本插件的分组上，采用的是互斥的，也就是采用了就不能重复采用，这个有点不方便

## 一、关于分组插件复用
实际上我们在分组的时候，可能同一个插件在多个分组里同时出现。比如1pass之类的密码插件。
按照现在的分组，1pass就只能在一种分组里出现了。。不太方便，这个是否可以考虑改进为同一个插件可以在多个分组里使用。


## 二、关于分组和情景的探讨

这2者的理解颇为费解和麻烦，是否可以采用下面👇的简单逻辑

1，分组就是切换不同的插件。
2，情景就是完整的东西（新的分组+规则），这种也比较符合逻辑。情景嘛，应该是完整的一整套

比如情景是工作，就是： 分组(无广告)+规则1
比如情景是开发，就是： 分组(极简插件)+规则2

这样的好处就是，在不同的场景下，调用不同的分组和规则，也可以减少单次调用过多的规则让网站变卡。
这样子的话，规则也就可以更灵活了

**Comment by gbsix** [comment]
完全赞同楼上的建议，扩展需要交叉放入不同的分组中，以适应不同的场景。

**Comment by JasonGrass** [comment]
> 辛苦作者了，非常感谢功能的增加。
> 
> 这里有一点小小的问题，提出来探讨下。 在本插件的分组上，采用的是互斥的，也就是采用了就不能重复采用，这个有点不方便
> 
> ## 一、关于分组插件复用
> 实际上我们在分组的时候，可能同一个插件在多个分组里同时出现。比如1pass之类的密码插件。 按照现在的分组，1pass就只能在一种分组里出现了。。不太方便，这个是否可以考虑改进为同一个插件可以在多个分组里使用。
> 
> ## 二、关于分组和情景的探讨
> 这2者的理解颇为费解和麻烦，是否可以采用下面👇的简单逻辑
> 
> 1，分组就是切换不同的插件。 2，情景就是完整的东西（新的分组+规则），这种也比较符合逻辑。情景嘛，应该是完整的一整套
> 
> 比如情景是工作，就是： 分组(无广告)+规则1 比如情景是开发，就是： 分组(极简插件)+规则2
> 
> 这样的好处就是，在不同的场景下，调用不同的分组和规则，也可以减少单次调用过多的规则让网站变卡。 这样子的话，规则也就可以更灵活了

收到，后面改一下，支持扩展可以交叉放在不同的分组中。

情景和分组，本身是相互独立的，他们只在配置规则时，可能会出现在同一个规则中（情景是触发器，分组是被执行的目标）
最近正在优化规则哪里的显示逻辑，看优化之后，会不会好一点。
