### ISSUE TITLE
增加“更新历史”选项卡

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#22]
二管家对于安装、卸载、更新扩展都会在底部右下角通知显示，点击历史标签也都会在时间线上提示全部更新信息，这样如果有哪个扩展在自动更新后出现了问题，就可以及时发现并回退旧版本。对于排查扩展很有用，希望可以借鉴。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/a0bb5714-6090-48a4-bc7e-824535ce75ab)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/a7998c7e-33c6-4873-a7bc-6dd009dc2b2f)

**Comment by gbsix** [comment]
也可以参考这个已经停更的[LOG扩展]( https://chrome.google.com/webstore/detail/extension-log/eiljhbjamiikjjldhnepillceohglbjh)

**Comment by JasonGrass** [comment]
二管家开源地址
[AInoob/NooBoss: NooBoss is an extension that handles your extensions like a boss!](https://github.com/AInoob/NooBoss )

**Comment by JasonGrass** [comment]
基本想法

以表格形式呈现，包含以下列：
时间：绝对时间 相对时间两种显示方式可切换
事件：安装 更新 卸载 启用 禁用，支持筛选？
图标：扩展图标
名称：扩展名称，优先别名，有 hover 操作：solo（仅显示此扩展的记录）
版本：扩展版本
备注：
    启用与禁用的原因：规则执行，手动切换分组，未知（在 chrome 管理页面或者被其他扩展管理工具禁用，这里要加 tooltip） 
    如果是因为规则执行被启用或禁用，则可以跳转到对应的规则（规则页面仅显示一条规则，且自动打开详情，提供回到规则设置主页的按钮）
备注需要带的上下文信息：规则 ID，分组ID

注意点：合并主动事件记录与浏览器事件监听记录，需要去重处理

表格上面的工具栏
1 时间显示方式切换
2 帮助链接跳转按钮
3 清空数据按钮
4 恢复显示全部（solo 状态下可见）
5 搜索框（扩展搜索）

还可以考虑加上浏览器本身的更新事件记录

技术
使用 index db 本地存储数据，最多保存 999 条或者 1 个月

**Comment by JasonGrass** [comment]
0.1.3 版本上线，后续发现一些小问题，下个版本修复上线。

**Comment by JasonGrass** [comment]
这个不是个高频功能吧，放个按钮也是跳转过去，没有打算在 popup 中显示历史记录

**Comment by JasonGrass** [comment]
暂时没有这样的想法，其实我对这个工具的定义是“默默无闻”式的，配置规则之后，不平时不关心这个扩展的存在。交互不想要太复杂。
