### ISSUE TITLE
增加“激活该扩展程序”快捷键

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#23]
如图

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/9f945120-6da8-4a92-8979-73762d4da384)

后期如果能给每个**分组**单独添加快捷键就更方便了。

**Comment by JasonGrass** [comment]
> 

GET 多谢提供建议，我先记录一下，开发排期会靠后一点点

**Comment by JasonGrass** [comment]
chat gpt: 

在 Chrome 扩展程序开发中，您可以使用 `chrome.commands` API 来让用户自行设置快捷键，并执行自定义功能。

首先，在您的扩展程序清单文件（manifest.json）中，您需要声明 `"commands"` 权限，并定义您希望用户设置的快捷键。例如：

```json
"commands": {
  "myCustomCommand": {
    "suggested_key": {
      "default": "Ctrl+Shift+D"
    },
    "description": "Execute my custom command"
  }
}
```

在上面的示例中，我们定义了一个名为 `myCustomCommand` 的命令，并建议用户将快捷键设置为 "Ctrl+Shift+D"。您可以根据自己的需求修改快捷键和命令的名称和描述。

然后，在您的扩展程序的 JavaScript 代码中，您可以使用 `chrome.commands.onCommand` 事件来监听用户按下快捷键的操作，并执行相应的自定义功能。例如：

```javascript
chrome.commands.onCommand.addListener(function(command) {
  if (command === 'myCustomCommand') {
    // 执行自定义功能
    console.log('用户按下了自定义快捷键');
    // 在这里编写您希望执行的自定义功能代码
  }
});
```

在上面的代码中，我们使用 `chrome.commands.onCommand.addListener` 方法来监听用户按下快捷键的操作。当用户按下快捷键时，如果命令与您定义的命令名称相匹配（在这个例子中是 `myCustomCommand`），则会执行相应的自定义功能。

请注意，为了让用户自行设置快捷键，您需要在扩展程序的选项页面或者设置页面中提供一个界面，让用户可以自定义设置快捷键的操作。然后，您可以使用 `chrome.commands.getAll` 方法来获取用户设置的快捷键信息。

```javascript
chrome.commands.getAll(function(commands) {
  console.log(commands);
  // 在这里处理用户设置的快捷键信息
});
```

在上面的代码中，我们使用 `chrome.commands.getAll` 方法来获取用户设置的所有快捷键信息，并在控制台打印出来。您可以根据自己的需求处理用户设置的快捷键信息。

请注意，用户设置的快捷键只能在 background 页面或者后台脚本中监听和处理，不能在 popup 页面或者 content script 中使用。如果您希望在 popup 页面中执行相应的功能，可以使用 messaging API 将信息从 background 页面传递给 popup 页面。

**Comment by JasonGrass** [comment]
[chrome.commands - Chrome Developers](https://developer.chrome.com/docs/extensions/reference/commands/ )

**Comment by JasonGrass** [comment]
发现激活扩展（打开 Popup）这个功能，是 chrome 自带的，设置了快捷键就有了

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/ac0f4eb4-16b8-4cb3-9925-469a9133a135)

**Comment by JasonGrass** [comment]
> 快捷键在百分102并没有显示，在猫眼117倒是有（前几天就发现了），难道对内核版本还有要求? 不应该啊。 正常如果扩展允许添加快捷键的话在chrome://extensions/shortcuts应该就可以设置，不分内核。麻烦检查一下怎么回事吧

这个需要浏览器本身支持

**Comment by JasonGrass** [comment]
这个就不清楚了，我只是在 chrome 上做测试，其它的 Chromium 内核浏览器暂时没有那么多时间处理。

简单看了一下，应该跟 manifest 版本有关系，在百分浏览器，如果是旧版本，会默认有这个，如果是新版本，则需要显式声明。但是 Chrome 不需要显式声明。
