### ISSUE TITLE
搜索功能失效

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#24]
在设置中开启“在 Popup 中切换分组时，启用当前分组扩展，禁用其它的扩展”选项后，搜索功能失效。win7x64

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/06c6041d-7a8a-475f-8c9e-51972f5e0209)

**Comment by JasonGrass** [comment]
> 

感谢反馈~ 确实一个 BUG 😭
