### ISSUE TITLE
搜索内容：不限于标题，还要包括介绍文字

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#28]
比如这个扩展名字是[Background Randomizer](https://chrome.google.com/webstore/detail/background-randomizer/meakmfmcecciafnbacdcfdfhfdifcgfg)，如果搜索说介绍明里的dark是搜索不到的，所以建议把搜索内容扩展到扩展的介绍文字，参照extension manager。

因为扩展多了，一下子可能想不到准确的名称（有些扩展名字也太过于简洁和不相关），这样的情况下一般搜索扩展介绍里的文字能大大增加搜索到的概率。如果以后能够加上扩展备注名，就更好搜索了。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/b06f2064-1199-45c3-88b6-412c37a0aace)

**Comment by JasonGrass** [comment]
收到，这个可以有~ 感谢提供建议
