### ISSUE TITLE
情景模式。不包含本身的话。extension-manager会被一直禁用 没办法管理

### ISSUE THREAD

**Issue by Whichbfj28** [JasonGrass/auto-extension-manager#3]
情景模式【匹配才打开】。不包含本身的话。extension-manager会被一直禁用 没办法管理

---

Extension Manager 0.0.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
嗯，确实没有过滤掉这个插件本身。
我优化一下
