### ISSUE TITLE
建议：网格视图图表下显示扩展名称和其他

### ISSUE THREAD

**Issue by kickTiger** [JasonGrass/auto-extension-manager#30]
如题，图标不见得记得都是些啥扩展，
- 网格模式下显示扩展名称，
- 优先显示扩展别名
- 可以把那个网络模式下浮窗里的删除按钮去掉，避免误触，基本上不需要删除插件。
要删除进去删除就是了，这里太容易误触了。
建议把这个按钮改成  锁定 🔒/ 解锁🔐，也就是 添加到固定分组里去。

感谢作者的辛苦，更新的功能非常及时，3Q！

**Comment by JasonGrass** [comment]
删除这个，问题不大，浏览器进行二次确认的。
我这里也加一个二次确认吧。

**Comment by JasonGrass** [comment]
已上线 

发现一个问题，浏览器为了性能考虑，在静置一小段时间后，扩展的后台逻辑就会被休眠。如果扩展想要执行后台逻辑，需要等待浏览器事件的触发，如打开/关闭/切换标签等。

所以，对于时间区间的匹配而言，实际的规则执行时间可能是不准确的，只能作为非精确场景下使用。
