### ISSUE TITLE
自动跳转到chrome应用商店搜索 & 分组可上下拖拽排序

### ISSUE THREAD

**Issue by BoltLi** [JasonGrass/auto-extension-manager#33]
如题，希望在搜索框搜索后，回车能自动跳转到chrome应用商店内搜索扩展的功能，方便扩展安装
以及右侧分组管理，配置成可上下拖拽的，也方便管理
![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/ef7a778e-99cc-4335-a906-f3899a1513fc)

**Comment by BoltLi** [comment]
这个组件显示上默认个人感觉没意义，我前面都设置了啥模式了，那就显示啥模式才是最直接的，显示默认还是不清楚默认是啥模式，开启的时哪个模式下的插件

![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/e7d9aa9e-2cf2-4ed0-991f-0a5d8ae4cda7)

另外这个非固定模式下的插件，我感觉可以参考之前的Extension manager的做法，在插件选区的右上角标志出来，可以避免重复选择
![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/ae69db87-7fe8-4552-8bbf-25e909832ce3)

感觉这些地方再优化下，这个扩展就很完美了。

**Comment by JasonGrass** [comment]
这个搜索功能只搜索已经安装的扩展，搜索应用商店中的扩展，属于更大范围的扩展管理了，还是直接去应用商店搜索比较好。
分组管理这里的建议很棒，后面加上

**Comment by BoltLi** [comment]
> 这个搜索功能只搜索已经安装的扩展，搜索应用商店中的扩展，属于更大范围的扩展管理了，还是直接去应用商店搜索比较好。 分组管理这里的建议很棒，后面加上

这里我的意思是相对于就是调用了chrome扩展商店的搜索接口，直接回车就跳到chrome内搜索该扩展的，不回车就不会跳转到chrome扩展商店搜索。至于显示出来的搜索结果，肯定还是已经安装到扩展中匹配到的扩展

**Comment by JasonGrass** [comment]
这个交互非常奇怪，一般用户对这里跳转到 chrome 应用商店，不会有任何预期

**Comment by BoltLi** [comment]
>

**Comment by BoltLi** [comment]
我觉得还行，之前用另外一个很受欢迎的扩展的时候常用这个功能，在已经安装到扩展中搜不到，直接回车就到应用商店中搜索，不用再在地址栏一步步输入应用商店地址，还是挺方便。
