### ISSUE TITLE
在扩展界面加入"按开启频率排序"功能 ？

### ISSUE THREAD

**Issue by GEEKCX** [JasonGrass/auto-extension-manager#34]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/31879429/02cc9fc7-dad2-49ec-ac7f-4519f71024d6)
排序后更快找到要用的扩展，望采纳。
![image](https://github.com/JasonGrass/auto-extension-manager/assets/31879429/2033e825-879d-4f0a-84cf-367460d3dfe1)
以及这个搜索框是否太窄了点，若可以的话 长一丢丢。目前各项功能完善，感谢开发者，已经替代旧（扩展管理器）

**Comment by JasonGrass** [comment]
开启频率怎么定义啊，如果是指直接在浏览器中点击其它扩展的图标，我这里好像没办法知道。

**Comment by GEEKCX** [comment]
> 开启频率怎么定义啊，如果是指直接在浏览器中点击其它扩展的图标，我这里好像没办法知道。

不是指点击其他扩展的图标，指的是最近打开关闭过的扩展。尤其是下面灰色的未打开的图标，最近有使用过的扩展排序在最前。长期未打开过的扩展在最后面。
![image](https://github.com/JasonGrass/auto-extension-manager/assets/31879429/e458aea1-d675-48e1-b9af-682ea44daff2)
