### ISSUE TITLE
URL 匹配 包括 查询参数和锚点部分

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#35]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/9c7331ec-40ce-4d8b-8b61-dbaf758b3e87)

我如果想匹配特定网址：* baidu.com/s?wd=hello&rsv_ spt=1#5 * 是不能返回任何结果的
目前最长只能匹配 https://www.baidu.com/s*

请问能否增加匹配长度，很多时候只需要匹配域名中具有相似特征的一组页面，而不需要匹配整个域名。

谢谢！

**Comment by JasonGrass** [comment]
URL 匹配设置时，添加了一个选项，可以选择完整 URL 匹配
