### ISSUE TITLE
标记固定分组中的扩展

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#36]
分组管理：新建的分组下面的标签“不在此分组”中标记固定分组中的扩展，便于区分哪些已经属于固定分组，避免重复添加。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/aa1881dd-db4f-4279-b44c-a121b23e651c)

**Comment by JasonGrass** [comment]
升级到 0.1.5 版本之后，打开这个开关，就有了

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/6568f3cf-eba0-4709-8242-9bda27175090)

**Comment by JasonGrass** [comment]
就是在这个界面

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/55655ffb-9597-4d43-b9bf-6086faf19be1)


没有吗？
你的版本是多少了？
看下控制台有没有报错

**Comment by JasonGrass** [comment]
感觉藏了个 BUG

**Comment by JasonGrass** [comment]
> 0.1.5 百分102内核不显示，猫眼117内核也不显示。控制台怎么查看？

确实一个 BUG，默认值的问题。你把那个配置开关关闭然后再重新打开就可以了。

**Comment by JasonGrass** [comment]
> 按照以前固定分组的逻辑，如果扩展存在固定分组中，新建的分组添不添加那些（固定分组中的）扩展，默认都会在新分组中一并打开。

是，切换分组，会打开选中分组和固定分组中的扩展，关闭其它扩展。
也就是：固定分组中的扩展，被认为是常驻扩展，一定会在切换分组时被打开。

期望的逻辑是怎样的？

**Comment by JasonGrass** [comment]
> 默认应该就是这样的：固定分组中的扩展，被认为是常驻扩展，一定会在切换分组时被打开。
> 
> 其他分组中点击已经在固定分组中的扩展有一个添加的动作，会误认为固定的扩展需要都重新添加一遍（其实添不添加都一样效果）。如果把固定分组的扩展直接全都自动添加到新分组中是不是更好理解一些。

确实没想到可能会有这个误解，我后面加个提示吧。
如果出现了  “在其它分组中添加已经在固定分组中的扩展”  的情况，在首次给一个提示，明确说明一下你提到的这个问题。
