### ISSUE TITLE
区分活动的分组

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#37]
为了便于区分正在使用的分组，点击图标后应该在分组处显示**当前启用**的分组名称，而不是在任何状态下都显示“未选择分组”。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/57a9ecd3-00ec-40cf-a0ab-1fb40e0eb3fa)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/3400c5c6-a12f-4e21-aefa-5f0bd1d98fc7)

**Comment by BoltLi** [comment]
这里的确应该，前面设置了啥分组就要显示啥分组，即使有启动了其他一些插件，但是前面已经选中了啥分组，那这里就应当显示啥分组。
情景模式匹配的扩展已经由情景模式表示了，而前面启动的模式到后面也应该显示啥模式才是对的，而且，在选择分组的时候，如果已经在某个网址内，最终的作用j结果也应该是两个模式共同器作用的所有的扩展都要启动。

**Comment by BoltLi** [comment]
这里这个显示对应打开的分组功能，导致一个是不能启动其他扩展，另外一个问题是情景模式失效，打开网址，情景模式匹配的扩展是打开的，等一会情景模式对应的扩展又会自动关闭。
另外也反馈一个情景模式的问题，一个是大方框太占地方，另外一个是配置多了，不会自动换行 ，需要右拉滚动条才行，显示效率太低了
![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/b3d95c3a-7231-4038-99a8-147a0b4f32e5)

**Comment by JasonGrass** [comment]
不用启用其它扩展的 BUG，已修复等待审核，在 0.2.1 版本再看看
