### ISSUE TITLE
排序空白，导入失败，规则保存失败

### ISSUE THREAD

**Issue by OrangeCatSleepless** [JasonGrass/auto-extension-manager#39]
最新的 0.1.6版本

1. 如果开启 ”按照启用频率进行排序“ 功能会有极大概率导致扩展管理以极快速度刷新后变成空白

![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/0e452993-782f-4652-a253-a59e40fd2c15)

2. 尝试导出数据后重新导入，但提示导入失败，这里还有一个问题,点击“恢复默认”仅重置了通用设置页面，其他页面并没有重置，这是原本就这样设计的吗？如果是能不能出一个重置全部数据？

![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/1c26bd13-11db-40ca-9f1b-86ba39d522ec)

3. 存储未达单项8kb限制，但保存规则失败

![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/7b0d9397-007a-4000-8749-111d2695e0bf)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/9ed9afdc-3cb6-45f0-a6dd-bf9e27479100)

**Comment by JasonGrass** [comment]
1 显示空白的问题，是个 BUG，正在修复  
可以先不使用按照频率排序功能

2 保存超过存储限制的问题  
看起来是我之前对存储限制的理解有点问题，还得看看具体怎么回事

3 “恢复默认”仅重置了通用设置页面  
这个是设计如此，后面可以修改一下文案，并加一个清空全部配置的选项

**Comment by JasonGrass** [comment]
存储空间的问题，找到原因了，被使用的一个库给坑了，后面可以修复

**Comment by JasonGrass** [comment]
> 1 显示空白的问题，是个 BUG，正在修复 可以先不使用按照频率排序功能
> 
> 2 保存超过存储限制的问题 看起来是我之前对存储限制的理解有点问题，还得看看具体怎么回事
> 
> 3 “恢复默认”仅重置了通用设置页面 这个是设计如此，后面可以修改一下文案，并加一个清空全部配置的选项

已在 0.1.8 版本处理

附录  
[Quota limits for chrome.storage are missing · Issue #135 · GoogleChrome/developer.chrome.com](https://github.com/GoogleChrome/developer.chrome.com/issues/135 )
