### ISSUE TITLE
【建议增加定时开启关闭功能】

### ISSUE THREAD

**Issue by Whichbfj28** [JasonGrass/auto-extension-manager#4]
比如我9-12点的时候关闭扩展
12-18的时候打开这些扩展

**Comment by JasonGrass** [comment]
get，这几天加上

**Comment by JasonGrass** [comment]
> 比如我9-12点的时候关闭扩展 12-18的时候打开这些扩展

实现的时候，发现一些问题。
1 如果需要支持时间段的开启，后台需要开启一个定时器轮询，会比较影响性能
2 如何确定在临界时间，是不是正好在使用插件？如果正好在使用，突然关闭了，会造成体验上的影响。

更建议使用手动开启或关闭的方式，在配置中打开切换分组时执行扩展的启用与禁用，可以实现批量的手动操作。
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/7947effb-76b5-42cd-885f-d187d57f91a4)

另外，想问一下，这个按时间进行打开或关闭扩展的需求，有具体场景吗？

**Comment by Whichbfj28** [comment]
> > 比如我9-12点的时候关闭扩展 12-18的时候打开这些扩展
> 
> 实现的时候，发现一些问题。 1 如果需要支持时间段的开启，后台需要开启一个定时器轮询，会比较影响性能 2 如何确定在临界时间，是不是正好在使用插件？如果正好在使用，突然关闭了，会造成体验上的影响。
> 
> 更建议使用手动开启或关闭的方式，在配置中打开切换分组时执行扩展的启用与禁用，可以实现批量的手动操作。 ![image](https://user-images.githubusercontent.com/10756994/261618507-7947effb-76b5-42cd-885f-d187d57f91a4.png)
> 
> 另外，想问一下，这个按时间进行打开或关闭扩展的需求，有具体场景吗？


上午摸鱼开启摸鱼插件。。
下午上班开启上班插件。。。

**Comment by Whichbfj28** [comment]
也不用太精确到秒。比如可以半小时。或者1小时什么的。不知道对性能影响大不大。

**Comment by JasonGrass** [comment]
已上线

发现一个问题，浏览器为了性能考虑，在静置一小段时间后，扩展的后台逻辑就会被休眠。如果扩展想要执行后台逻辑，需要等待浏览器事件的触发，如打开/关闭/切换标签等。

所以，对于时间区间的匹配而言，实际的规则执行时间可能是不准确的，只能作为非精确场景下使用。

**Comment by Whichbfj28** [comment]
足够了。
