### ISSUE TITLE
固定/取消固定

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#40]
这个钉针按钮当前逻辑是添加到“固定分组”，我觉得有点重复，毕竟在后台已经有了固定分组的选项，在列表也都有标识。固定分组里的扩展设置后，一般是不需要频繁调整的。倒是“固定/取消固定”到工具栏比较符合逻辑，使用频率也更高些。

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/5a44b0f6-109d-4c70-920e-0b605861551d)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/68337d68-8a7f-4a0e-b16a-688e5e17c542)

希望可以考虑优化。

**Comment by JasonGrass** [comment]
这个是之前有个同学提的建议 #30 
不过这个图标确实应该改一下，容易引起误会。

固定都标题栏，这个 chrome 没有给 API，只能在原生的扩展列表中处理。
