### ISSUE TITLE
跳转应用商店可选Chrome和微软

### ISSUE THREAD

**Issue by BoltLi** [JasonGrass/auto-extension-manager#49]
如题，希望增加一个选项，因为就目前还是Chrome应用商店上的更为全面，版本更新也快，希望跳转应用商店增加一个选择哪一个的选项，可以考虑重新调整下布局
![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/9a3537ba-75dc-43b5-b8c5-de5f9a907c40)

**Comment by BoltLi** [comment]
另外说一下，评价这里没法正确跳转，例如我是从Chrome安装的，但是我使用的edge，结果他跳转到微软应用商店，而且显示出错。这里也建立按照扩展安装来源调整下跳转链接
![image](https://github.com/JasonGrass/auto-extension-manager/assets/42888380/ce958322-ea60-474a-b8a9-7fbd4f3cb842)

**Comment by JasonGrass** [comment]
感觉，大部分扩展微软商店更新慢的原因，是微软商店审核太慢了，chrome 这边几个小时，微软要几天

**Comment by JasonGrass** [comment]
update at 0.2.4
