### ISSUE TITLE
建议适配Firefox

### ISSUE THREAD

**Issue by staofr** [JasonGrass/auto-extension-manager#5]
如果可能 建议适配Firefox
非常感谢

**Comment by JasonGrass** [comment]
参考资料

[构建一个跨浏览器的扩展程序 - Mozilla | MDN](https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension )  

[Chrome 不兼容情况 - Mozilla | MDN](https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities )  

[利用Firefox开发者网站，转换Chrome插件为Firefox插件 - 知乎](https://zhuanlan.zhihu.com/p/163535578 ) 

[Firefox扩展开发 - 入门篇 - 知乎](https://zhuanlan.zhihu.com/p/390304772 )

**Comment by JasonGrass** [comment]
management.uninstall is not supported  
This API has not been implemented by Firefox.

**Comment by JasonGrass** [comment]
firefox 的 API 根本不支持插件管理的功能，哎~ 还折腾了小半天~ 

[management.setEnabled() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/setEnabled )

> The function allows enabling/disabling of `theme addons` , but will return an error if used to enable or disable other types of web extension.

**Comment by leic4u** [comment]
Requested supporting in https://github.com/mdn/browser-compat-data/issues/23106

**Comment by leic4u** [comment]
I have requested supporting in [Mozilla Connect](https://connect.mozilla.org/t5/ideas/support-a-extension-enable-disable-the-other-extensions/idi-p/57348?emcs_t=S2h8ZW1haWx8ZGlnZXN0X25vdGlmaWNhdGlvbnxMV0MyUEZSMzNVNUsxT3wtMXxPVEhFUlN8aEs), please vote for it.
