### ISSUE TITLE
扩展别名增强

### ISSUE THREAD

**Issue by OrangeCatSleepless** [JasonGrass/auto-extension-manager#50]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/4ef5068c-0c28-4538-a862-7bc2cdc57c47)
建议再加两个筛选项 不存在备注/别名

**Comment by JasonGrass** [comment]
release at 0.2.6 
https://github.com/JasonGrass/auto-extension-manager/releases/tag/v0.2.6
