### ISSUE TITLE
悬浮信息提示

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#51]
鼠标移到扩展**图标**上的时候提示当前版本号、最近一次更新时间、扩展备注（优先展示）？类似 [simpleextmanager](https://chromewebstore.google.com/detail/kniehgiejgnnpgojkdhhjbgbllnfkfdk)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/98303833/53166e79-01dd-4605-aca1-d6f8bbfbc31c)

这属于可有可无的需求，如果有难度或者不想加都可以理解。

**Comment by JasonGrass** [comment]
你知道好多扩展管理工具 😂，有点厉害，怎么发现的~ 

功能不难，但是日常使用中，其实并不会特别关注这些信息的展示。hover 显示的存在感很强，反而会影响功能性的操作。
如果要做，也是放在一个独立的 info icon button 中。

另外，hover 会有一个交互冲突，在网格模式下，hover 是显示操作菜单，同时显示额外的信息的话，UI 会很杂乱。

所以，暂时先不考虑这个功能了，不过还是很谢谢你的建议~
