### ISSUE TITLE
功能探讨，Popup 中突出显示匹配当前站点的扩展

### ISSUE THREAD

**Issue by OrangeCatSleepless** [JasonGrass/auto-extension-manager#52]
能否当匹配到指定网址时，在插件中单独分隔一个区域用来显示预设好的推荐插件？

或者使用不同颜色的圆点表示，并且提前对应插件的排序这样就不用单独分一区域了，不清楚那种方法比较好实现

![image](https://github.com/JasonGrass/auto-extension-manager/assets/58691431/ff40e1dc-0f09-4c15-8b30-65bf0057fcf7)

主要是因为一些插件相互冲突，比如针对 chat.openai.com 生效的一些插件，同时开启会导致错误，需要根据使用情况来手动开启

如果太复杂的话就算了，目前插件已经非常好用了👍

**Comment by JasonGrass** [comment]
一个很有趣的想法，
内置 “预设好的推荐插件” 做不了，那得弄个后台维护数据，
不过你这个功能是可以实现的，让用户自己设置扩展的关联站点就行了 
确实有点意思，整~

**Comment by JasonGrass** [comment]
release  
https://github.com/JasonGrass/auto-extension-manager/releases/tag/v0.2.7
