### ISSUE TITLE
Toggle Groups on/off

### ISSUE THREAD

**Issue by kacheng** [JasonGrass/auto-extension-manager#54]
Can you add an ability toggle groups on/off?

Currently you can choose a group and disable all others.
I would like to enable/disable 2 or more groups at the same time.

Thanks!

---

Extension Manager 0.2.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
release at 0.3.0 

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/f75dd04f-f7b6-4a99-9553-59692af5201d)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/3b6c32da-69df-42dc-864a-0501db47c3d5)

**Comment by kacheng** [comment]
So fast! 
Thank you!
