### ISSUE TITLE
高频禁用插件导致 New-Bing-Anywhere background 消息无法正确处理

### ISSUE THREAD

**Issue by haozi** [JasonGrass/auto-extension-manager#55]
## 问题插件 
https://chrome.google.com/webstore/detail/new-bing-anywhere-bing-ch/hceobhjokpdbogjkplmfjeomkeckkngi/reviews?hl=en

## 配置规则
<img width="850" alt="image" src="https://github.com/JasonGrass/auto-extension-manager/assets/4150641/d0ee890a-f53b-4eef-b674-249bdcd1ce54">
<img width="875" alt="image" src="https://github.com/JasonGrass/auto-extension-manager/assets/4150641/ae161408-2089-43e2-989d-52b3c1aa3a5e">

## 复现问题，这个按钮点击无效
<img width="547" alt="image" src="https://github.com/JasonGrass/auto-extension-manager/assets/4150641/a2cf4853-8f6b-4a81-b71e-8df3cb20973e">

## 原因复盘
点击按钮时，这个插件会向 background 发送消息，这时候被切到 about:blank, 插件立马被禁用，导致无法正确处理 background 回调

## 建议
1. 禁用插件时增加延时和节流逻辑
2. 匹配后打开选项，在触发第一个 tab 规则时启用，在所有相关 tab 全部关闭后 x 秒，禁用插件

---

Extension Manager 0.3.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
这个界面在哪里？
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/9b8669be-4908-48db-b21f-0001235d58db)

**Comment by JasonGrass** [comment]
确实，延迟 500ms 再禁用就没啥问题了。

**Comment by haozi** [comment]
赞，效率啊
