### ISSUE TITLE
部分拓展图标显示模糊

### ISSUE THREAD

**Issue by czz404** [JasonGrass/auto-extension-manager#59]
![pic_1695906855.png](https://s2.loli.net/2023/09/28/TH1cRIYaovxEj7r.png)
部分拓展图标显示模糊，之前版本正常

**Comment by JasonGrass** [comment]
麻烦把屏幕分辨率发一下，我调查看看

**Comment by czz404** [comment]
<img width="810" alt="截图_20230928223909" src="https://github.com/JasonGrass/auto-extension-manager/assets/64689594/60e25762-3121-465b-8985-a441e8285fac">
感谢回复

**Comment by JasonGrass** [comment]
也是个 BUG，图标大小的判断排序有点问题。已修复，升级到 0.3.4 就 OK 了。
明天早上应该就可以了

**Comment by czz404** [comment]
感谢

**Comment by JasonGrass** [comment]
哈哈，是我要谢谢你，帮忙发现并报告了 bug  🤣🤪

**Comment by czz404** [comment]
更新之后没问题了👍
