### ISSUE TITLE
网格视图，启用与禁用扩展之后，显示位置的切换

### ISSUE THREAD

**Issue by aliangzhihuo** [JasonGrass/auto-extension-manager#62]
禁用某个扩展的时候，好像不会马上显示在已禁用的扩展列表里，要重新点击扩展管理器重新打开一下（启用也是一样好像）
![image](https://github.com/JasonGrass/auto-extension-manager/assets/12654292/d03dcffa-f6e3-4fc3-9311-a50bf0cfbd17)

**Comment by JasonGrass** [comment]
在 0.3.5 版本中处理

**Comment by aliangzhihuo** [comment]
还有好像显示会卡，不知道是不是我电脑原因

**Comment by JasonGrass** [comment]
是打开的时候卡，还是启用禁用扩展之后，刷新页面卡？

可以录个屏，看下具体情况

**Comment by aliangzhihuo** [comment]
打开的时候，按这种格式显示的时候，今天好像比昨天好点了
![image](https://github.com/JasonGrass/auto-extension-manager/assets/12654292/c78a78f3-548c-4631-8b5e-7b4dac0b640a)
