### ISSUE TITLE
增加个在crxsoso搜索的功能？

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [JasonGrass/auto-extension-manager#63]
默认搜索扩展是在谷歌应用商店  加个crxsoso的搜索源如何？

---

Extension Manager 0.3.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
在 0.3.5 版本中添加搜索源的配置
