### ISSUE TITLE
Popup，添加按分组显示扩展的 UI

### ISSUE THREAD

**Issue by 2990844646** [JasonGrass/auto-extension-manager#64]
就是如图所示的这种能够手动调整插件显示顺序的功能(o゜▽゜)o☆
（动图来自于一个同类插件，地址：https://chrome.google.com/webstore/detail/extmanager/bgejgfcdaicmfbfphchgcdgnpnbcondb?hl=zh-CN ）
![GIF 2023-9-30 11-44-18](https://github.com/JasonGrass/auto-extension-manager/assets/146503193/56157eae-b8a4-4dd4-9231-62b7d5f16801)

**Comment by JasonGrass** [comment]
感谢你的建议，不过暂时不考虑这个功能。

现在影响排序的有两种方式：  
1 如果需要经常启用禁用某几个扩展，可以打开 `排序：按照启用频率进行排序` 这个配置，常用的扩展就会在前面显示
2 如果是针对特定的网站，想要将某几个扩展靠前显示，可以在规则设置中，选中 `在 Popup 中置顶显示扩展`，动作那里可以选 `无`，这样可以根据不同的站点，置顶显示不同的扩展。（PS 如果是想要永远置顶某些扩展，匹配条件中选择所有的操作系统类型，就相当于条件永远成立了）

或者，你有其它什么具体的应用场景，是上面两个功能无法满足的，需要自定义排序这个功能才会更方便。
可以描述一下你遇到的具体需求场景。

**Comment by JasonGrass** [comment]
哈哈，太客气了，不算叨扰啦，有想法就提出来，挺好的。
你这里其实提到了很重要的一点，就是分组问题。虽然现在有分组功能，但是在 popup 中显示时，并没有直观体现出分组。
这里其实可以加一个配置的，按分组显示全部扩展（当前是按是否启用来分类的）
我后面看看怎么弄~

**Comment by 2990844646** [comment]
Wow！我之前心里就是这么想的(≧∇≦)，因为这个插件真的很棒，又是靠爱发电的，实在不好意思向您提要求就又把话憋回去了。。。期待您今后的开发，也祝您的事业蒸蒸日上ヾ(●゜ⅴ゜)ﾉ
