### ISSUE TITLE
好像显示会有点卡，不知道是不是我电脑原因

### ISSUE THREAD

**Issue by aliangzhihuo** [JasonGrass/auto-extension-manager#65]

**Comment by JasonGrass** [comment]
可以帮忙录个屏吗，我看看具体是哪一部分会比较卡

**Comment by aliangzhihuo** [comment]
https://github.com/JasonGrass/auto-extension-manager/assets/12654292/66c00bcc-45e4-48f9-bb28-70368e1a3842

**Comment by JasonGrass** [comment]
0.3.8 版本做了一些优化，不确定是不是你这里卡的原因，升级之后，帮忙再看看

**Comment by JasonGrass** [comment]
@aliangzhihuo 升级到新版本之后，有所改善吗？

**Comment by aliangzhihuo** [comment]
好像还是是跟电脑有点关系，公司的电脑就挺快的。。

https://github.com/JasonGrass/auto-extension-manager/assets/12654292/f963936f-27ff-4b0e-9eb8-56e7151d820b

**Comment by aliangzhihuo** [comment]
两款扩展对比                                                                                                                                                             

https://github.com/JasonGrass/auto-extension-manager/assets/12654292/f007be9d-b815-4336-a666-1799d498cf7a

**Comment by aliangzhihuo** [comment]
两款扩展对比                                                                                                                                                             

https://github.com/JasonGrass/auto-extension-manager/assets/12654292/f007be9d-b815-4336-a666-1799d498cf7a

**Comment by JasonGrass** [comment]
这就有点难办了，得找一台比较卡的电脑来调试开发  😂

**Comment by y9287** [comment]
> 两款扩展对比
> 
>  20231010_222423.mp4

设置里面有个网络右键显示菜单勾选下，我怀疑是由于悬浮限制菜单，导致延迟。

经过两款插件的对比，我发现另外一个插件的显示虽然相对快，但是他点击图标和到插件内容显示出来明显有点延迟，而当前插件是你点击之后反应快，但是插件内容相对有加载感。

**Comment by aliangzhihuo** [comment]
最近好像好一点了。

**Comment by aliangzhihuo** [comment]
好像是adguard程序的关系，设置了一下好一点了。
