### ISSUE TITLE
Filter on extensions

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#67]
Hi there,

Could you please make a new feature to show extensions that do not have a group assigned? If I have e.g. 300+ extensions, it's hard to filter on just the extensions that do not have a group assigned.

Furthermore, if I have added extensions to the fixed group, then I would like to hide them from other groups. If I have 100 fixed extensions in the fixed group and I create a new group, I don't need to see the same 100 extensions in the list. The extensions in the fixed group will always be loaded in my browser, so it doesn't need to be shown every time I create a new group.

**Comment by JasonGrass** [comment]
A new feature of quick filter has been added in version 0.4.0.  
Like this:  
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/1887bab1-d9e7-4bc7-9f32-a495fb56346d)

This should be helpful for your issue.

**Comment by chaoscreater** [comment]
Thank you! <3
