### ISSUE TITLE
网格视图下划过图标弹出详细界面会阻挡旁边扩展的操作

### ISSUE THREAD

**Issue by miaonai** [JasonGrass/auto-extension-manager#68]
![详细操作](https://github.com/JasonGrass/auto-extension-manager/assets/67116517/de19fbf3-0603-4981-9652-1f08dd63cdcf)

例如，要操作左边那个扩展，如果鼠标划过右边扩展的图标就会快速的弹出详细操作，从而阻挡了操作左边的扩展。想操作左边的扩展就要绕过右边的那个图标去点左边。

靠边的第2或第3个扩展都会有这个问题。纵向划动鼠标操作还好，横向划动就会被各种阻挡，有点小麻烦。

如果方便的话，希望可以加个小延迟再打开详细操作界面，或者用其他更好更简单方法也可以。

**Comment by JasonGrass** [comment]
在 0.4.1 版本中，添加了使用右键菜单打开的配置。
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/21f31132-1314-415e-beff-499c274bf215)
