### ISSUE TITLE
匹配才打开导致无法开启扩展程序设置页面

### ISSUE THREAD

**Issue by name8102** [JasonGrass/auto-extension-manager#69]
当设置规则为匹配才打开时，开启扩展程序的设置页面会自动禁用该扩展程序，之后设置页面也会关闭。

虽然可以在匹配的 url 中添加设置页面的 url，但这样多少有些不便。而且某项规则开启多个扩展时，打开某个扩展的设置页面会启用不必要的扩展。

希望能将插件自身的设置页面加入特例，任何情况下不会在设置页面禁用对应的插件。

**Comment by JasonGrass** [comment]
Thanks，发现了这个很有趣的 BUG ~  😂

**Comment by JasonGrass** [comment]
已在 0.4.2 版本处理并发布
