### ISSUE TITLE
新增规则时选择扩展组会自动选择固定分组

### ISSUE THREAD

**Issue by miaonai** [JasonGrass/auto-extension-manager#70]
新增规则时选择扩展组会自动选择固定分组
![固定扩展](https://github.com/JasonGrass/auto-extension-manager/assets/67116517/eba352d1-17a0-4609-bec5-28dd18c6b536)

刷新一下设置界面后，虽然编辑时没有自动选择，但最后完成时还是显示选择了固定分组
![固定扩展2](https://github.com/JasonGrass/auto-extension-manager/assets/67116517/e2f4a516-c856-4791-a6e3-a16119862bdb)

再刷新一下又没了？很奇妙
![固定扩展3](https://github.com/JasonGrass/auto-extension-manager/assets/67116517/fbb03595-660a-4cf7-ae0a-22d05dd6bead)

**Comment by JasonGrass** [comment]
记录
使用正则 

`find.*(?<!=)=(?!=)(?!>)`  可以发现其它地方类似的书写错误，不过确实就这一个地方

**Comment by JasonGrass** [comment]
感谢反馈 BUG，已在 0.4.3 版本中修复，正在审核中，1 小时之内应该会上线。

如果发现应用商店版本已经更新，则可以使用 
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/dda13444-864e-4c69-88e1-b48e66bdfdd8)
来手动强制更新
