### ISSUE TITLE
【建议】能否考虑在扩展图标上点击“鼠标中键”或“修饰键 + 鼠标左键”，实现相当于在工具栏的扩展图标点击“鼠标左键”的效果

### ISSUE THREAD

**Issue by C1og** [JasonGrass/auto-extension-manager#71]

**Comment by JasonGrass** [comment]
`在工具栏的扩展图标点击“鼠标左键”的效果`  是指之前启动扩展吗，如打开选中扩展的 popup ?

这个实现不了，浏览器没有提供相关的 API，打开扩展只能由用户亲自操作。
包括将扩展固定到浏览器工具栏，也是必须由用户亲自操作，浏览器没有相关的 API。

**Comment by JasonGrass** [comment]
不过，我也挺想要这个功能的，这样就可以隐藏好多扩展，工具栏变得更整齐。
浏览器应该是避免功能被滥用吧。
