### ISSUE TITLE
New Logo is literally just tailscale

### ISSUE THREAD

**Issue by aidan-gibson** [JasonGrass/auto-extension-manager#72]
First off, thank you for making this extension, it's fantastic!

But I'm not sure why you updated the old logo? It looked pretty good.

And the new logo is nearly the same as https://tailscale.com/
![Tailscale-Logo-Black](https://github.com/JasonGrass/auto-extension-manager/assets/20917687/993c5f10-8e91-42d8-ab0f-f46913136e66)

**Comment by JasonGrass** [comment]
Thank you for your feedback. I have communicated with the author who created the logo, and he is considering designing a new one. 

the old logo was designed by midjourney, a friend designed a new one, more streamlined I think. 

if cannot find a better new one, I will restore the old logo.
