### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#73]
Hi there,

Really love your extension and just wondering if you have any plans to support Firefox in the future? I use both Firefox and Vivaldi (Chromium) and would love to have this extension in Firefox as well.

**Comment by JasonGrass** [comment]
I'm so glad you like it, but unfortunately, this feature cannot be implemented on Firefox.

Firefox does not provide a critical API for enabling and disabling extensions.

---

[management.setEnabled() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/setEnabled )

> The function allows enabling/disabling of theme addons, but will return an error if used to enable or disable other types of web extension.

**Comment by chaoscreater** [comment]
Oh ok, that's a shame.

I found this addon here and it seems to be able to enable/disable other addons?
https://addons.mozilla.org/en-US/firefox/addon/extensions-manager/

**Comment by JasonGrass** [comment]
Thank you for the clue provided, however, I found that this extension does not work properly on Firefox. You can check out the reviews of this extension. The original author might have just migrated the extension from Chrome without noticing this issue.

<https://addons.mozilla.org/en-US/firefox/addon/extensions-manager/reviews/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org>

**Comment by chaoscreater** [comment]
Yes you're right, I just tried the addons and they don't work :(

That's OK, maybe one day Mozilla will open the API for this :)
