### ISSUE TITLE
Automatic reload page just once?

### ISSUE THREAD

**Issue by chaoscreater** [JasonGrass/auto-extension-manager#75]
Hi there,

I have a couple of Rules that will automatically reload the tab when I browse to the site. The rule is set to load the addons only when I browse to the site, which means that they will unload when I leave the site.

The problem is that when I switch to another site and then switch back, the same page will reload again - e.g. from Google -> Github -> Google. I know this is normal behaviour, but some addons can still work even if the webpage is not reloaded.

For example, let's say I browse to Github.com and I have addons A, B and C.

1. Browse to Github.com, addons A, B and C are loaded.
2. Leave Github.com, addons A, B and C are unloaded.
3. Browse to Github.com again, addons A, B and C are loaded. At this point, even if the webpage isn't refreshed, addons A and B will still work without reloading the page, but addon C will require the page to be reloaded.

The 3 addons all belong to the same group. So it doesn't make sense to separate addons A and B into group #1 and disable page reload, and have addon C in group #2 with page reload enabled.

Ideally, there should be another option to allow the page to only be reloaded just once. The user will then have to reload manually afterwards. Perhaps there can be a timer set on the site - e.g. if page is reloaded already, wait another 10 minutes before the page will automatically be reloaded again.

I'm not sure how this can be achieved, but it would be great if this could be made more flexible :)

**Comment by JasonGrass** [comment]
you can set `Action` like this

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/660b4898-76a7-4af3-881e-50fa7ece03c4)

when you browse site a to another site b, the extension will not be disabled, until you close site a

**Comment by chaoscreater** [comment]
For the last condition where it says "ALL" tab not match, does it mean that if I have:

- 2 tabs for Github.com
- 1 tab for Gmail.com

and I browse from Github tab to Gmail tab, then close one of the Github tab, then the addons will still remain enabled?

The question is, what if I have hibernated tabs for Github.com? In my browser, I have a lot of tabs for the same domain (e.g. *.github.com) and some are hibernated, or some tabs might be pinned. In this case, not ALL of the Github tabs will be closed, which means the addons will still be enabled.

**Comment by JasonGrass** [comment]
yes, If you want more precise control, you can set up more detailed URL patterns.

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/33bea49b-2eae-40f4-b206-ff982be56077)

**Comment by chaoscreater** [comment]
Thanks. 

I don't have a specific URL pattern. I just need the following:

- Wildcard on the domain (Github.com)
- I may have multiple Github pages in my browser. Some may be active, some may be inactive (hibernated). If a Github tab is already refreshed, don't refresh it again until e.g. 10 minutes later. Alternatively, if the page is already refreshed, don't refresh it until it is closed and opened again.

**Comment by JasonGrass** [comment]
* The rule will not refresh any inactive/hibernated tab, it only refreshes the current tab.

* If you enable `Reload the current tab after enabled`， it means some extensions need webpage refreshing after their state is changed to `enable` from `disable`, if not, you did not enable `Reload the current tab after enabled` config.
