### ISSUE TITLE
【功能请求】把不常用的插件隐藏了，不小心全部关闭后，发现还挺麻烦

### ISSUE THREAD

**Issue by zhl111** [JasonGrass/auto-extension-manager#76]
我通常会把不常用的固定组隐藏。在试用情景模式时弄乱了。然后发现在这个插件管理的设置页面没有显示哪些插件是开启的，和可以打开或关闭的点击选择，现在的设置页面我一时都无法分辨哪些是我已开启或关闭的，能否补充一个界面？

---

Extension Manager 0.4.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
在分组管理页面，如果扩展名称的文字是灰色的，表示这个扩展没有启用。

在分组管理那里，直接启用或者禁用扩展，这个场景比较少。通常还是直接会在 popup 中操作。

--- 

具体到你现在的问题，你可以新建一个分组，将你想要开启的扩展（不管当前有没有开启），都放在这个分组中。
然后打开 `切换分组时，启用当前分组扩展，禁用其它的扩展` 这个配置，

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/6442b401-e95a-4ff9-96c0-2559b7e22c6d)

在 popup 中切换到这个分组，就可以了。

**Comment by JasonGrass** [comment]
嗯，这只是个临时的办法，弄完之后分组可以删掉。不过确实有点麻烦。

对于扩展非常多，然后因为规则配置或者分组切换，一下子禁用了很多扩展的情况，确实没有很好的撤销的办法。

要么就是一个一个点回来，要是就是配置另一个规则或者分组，批量启用回来。

PS 分组是可以多选的启用的

**Comment by JasonGrass** [comment]
0.5.0 版本升级了原来的别名管理页面，可以满足你这个需求了： 
`现在的设置页面我一时都无法分辨哪些是我已开启或关闭的，能否补充一个界面？`

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/3a6e0379-373e-4555-98c5-7c002cf498a0)
