### ISSUE TITLE
是否可以在“扩展别名”中添加‘’删除扩展”的功能，

### ISSUE THREAD

**Issue by GEEKCX** [JasonGrass/auto-extension-manager#78]
“扩展别名”直接改为扩展管理，不知道能否实现呢。
因为在网格视图下每删除一个插件，就要重新打开一次扩展图标然后再下拉寻找。
![image](https://github.com/JasonGrass/auto-extension-manager/assets/31879429/d92a5ec7-420a-41ed-a166-4e1997c24478)
还有上面的勾选框，能否再添加chrome 和edge 插件的勾选框。

**Comment by JasonGrass** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/74d4ee90-d42b-42e1-9425-249d4024e9ad)

哈哈哈，可以，我之前还不知道加一些什么扩展管理功能，这个主意不错。😎

**Comment by JasonGrass** [comment]
在 0.5.0 版本中发布

**Comment by GEEKCX** [comment]
> 在 0.5.0 版本中发布

太棒了！！
![image](https://github.com/JasonGrass/auto-extension-manager/assets/31879429/5e57faab-91a0-4242-b592-1cf65657ae9b)
筛选加入chrome和edge选项就更好了
