### ISSUE TITLE
【功能请求】添加原生插件管理器的功能

### ISSUE THREAD

**Issue by Ted-Liang** [JasonGrass/auto-extension-manager#80]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/133856115/64f37ed5-7a62-4c3b-a146-56f2158127cd)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/133856115/5fe22df5-568f-4541-b78d-049d3954bbd2)

原生插件管理器点击插件是能直接跳转出插件的功能使用的。
我想要利用我们这个拓展插件的排序，然后直接使用点击使用插件的功能。

这样就可以把固定在插件栏的数目弄少一点，可以隐藏起来，但是要用到插件的时候，又可以快速点击一下就可以操作。

**Comment by JasonGrass** [comment]
浏览器没有提供这个 API 

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/d94be6ef-ded9-4bbe-9f76-83ce395ec947)
