### ISSUE TITLE
昨天发现了这个插件宝藏，有些使用功能希望能考虑添加

### ISSUE THREAD

**Issue by y9287** [JasonGrass/auto-extension-manager#81]
1. 网络右键图标支持插件在线地址的访问。因为主页图标可能是插件作者的网站，由于习惯性去在线网站下载处查看评论和最新更新信息，感觉这个功能还是很有必要的。
2. 支持批量导出所有插件名称和插件在线地址，最好是 MD 格式的，这样方便后面整理备注。
3. 如果右键菜单能进行插件固定和取消固定，那是令人万分激动的事情了！

最后，希望插件越来越棒，作者不忘初心，渐入佳境！
                                                                                                              -- 改变就是好事。

---

Extension Manager 0.5.1
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
导出成 MD 这里没有太理解，`方便后面整理备注` 是什么场景？导出来之后，发表扩展分享之类的博客？

第3个，很遗憾，浏览器没有提供 API，我也挺想要这个功能的 

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/cc126565-07db-4ae1-939c-044dc8f3cc32)

**Comment by y9287** [comment]
> 导出成 MD 这里没有太理解，`方便后面整理备注` 是什么场景？导出来之后，发表扩展分享之类的博客？
> 
> 第3个，很遗憾，浏览器没有提供 API，我也挺想要这个功能的
> 
> ![image](https://user-images.githubusercontent.com/10756994/274798861-cc126565-07db-4ae1-939c-044dc8f3cc32.png)

第二个建议就是导出所有插件的清单（方便我写笔记备注这个插件是干嘛用的，浏览器多的情况下，也方便在其他浏览器快速安装插件）：
- [[扩展管理器（Extension Manager）](https://chromewebstore.google.com/detail/%E6%89%A9%E5%B1%95%E7%AE%A1%E7%90%86%E5%99%A8%EF%BC%88extension-manager%EF%BC%89/efajbgpnlnobnkgdcgcnclngeolnmggp)](https://chromewebstore.google.com/detail/扩展管理器（extension-manager）/efajbgpnlnobnkgdcgcnclngeolnmggp)
- [[清除历史记录，缓存和Cookie Chrome ™](https://chrome.google.com/webstore/detail/lcebokhepdpopanpieoopnjiehmoabfp)](https://chrome.google.com/webstore/detail/lcebokhepdpopanpieoopnjiehmoabfp)
- [[AdGuard浏览器助手](https://chrome.google.com/webstore/detail/fbohpolgemkbfphodcfgnpjcmedcjhpn)](https://chrome.google.com/webstore/detail/fbohpolgemkbfphodcfgnpjcmedcjhpn)
- [[Cubox](https://chrome.google.com/webstore/detail/bflmgpechpeohjfomgfdkkfcbhfcjohl)](https://chrome.google.com/webstore/detail/bflmgpechpeohjfomgfdkkfcbhfcjohl)

**Comment by JasonGrass** [comment]
0.5.2 版本已更新

https://github.com/JasonGrass/auto-extension-manager/releases/tag/v0.5.2
