### ISSUE TITLE
希望可以增加一个功能，在列表上面优先显示最近更新的扩展

### ISSUE THREAD

**Issue by PaulHerrero** [JasonGrass/auto-extension-manager#82]
---

Extension Manager 0.5.1
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60

**Comment by y9287** [comment]
> Extension Manager 0.5.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60

这个建议好，另外希望显示的插件名称能设置显示当前的版本号

**Comment by JasonGrass** [comment]
> > Extension Manager 0.5.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
> 
> 这个建议好，另外希望显示的插件名称能设置显示当前的版本号

显示当前的版本号这个，没有看懂是什么需求场景？
有具体案例说明一下吗？比如什么情况下，在 popup 中看到这个版本号会带来方便？

**Comment by y9287** [comment]
> > > Extension Manager 0.5.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
> > 
> > 
> > 这个建议好，另外希望显示的插件名称能设置显示当前的版本号
> 
> 显示当前的版本号这个，没有看懂是什么需求场景？ 有具体案例说明一下吗？比如什么情况下，在 popup 中看到这个版本号会带来方便？

也没有特别的使用场景，就是上面这位仁兄提到显示最近更新的插件，就想着是不是插件管理中就显示插件版本号会更锦上添花一点

**Comment by JasonGrass** [comment]
> > > > Extension Manager 0.5.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
> > > 
> > > 
> > > 这个建议好，另外希望显示的插件名称能设置显示当前的版本号
> > 
> > 
> > 显示当前的版本号这个，没有看懂是什么需求场景？ 有具体案例说明一下吗？比如什么情况下，在 popup 中看到这个版本号会带来方便？
> 
> 也没有特别的使用场景，就是上面这位仁兄提到显示最近更新的插件，就想着是不是插件管理中就显示插件版本号会更锦上添花一点

那应该不会，过多的信息只会让注意力分散，界面会显得杂乱。

**Comment by PaulHerrero** [comment]
> 在 0.5.3 版本添加，但是打开此选项可能会让 popup 加载速度变慢

感谢！
