### ISSUE TITLE
最新更新置顶排序，插件管理的时间排序与版本号显示

### ISSUE THREAD

**Issue by y9287** [JasonGrass/auto-extension-manager#83]
非常高兴看到了作者的积极更新，尝试新功能的同时发现了一些问题：

1. 「通用设置-显示内容」固定显示的最近更新（包含最近安装）的插件信息显示**并没有按照安装时间或者更新时间进行排序**
2. 「插件管理」模块无法按照最近安装或者最近更新排序进行管理（既然是管理面板了，是否可以增加一列版本信息显示呢）

刚刚体验了导出插件的功能，还支持自定义模块，非常 Nice!

---

Extension Manager 0.5.3
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
"「插件管理」模块无法按照最近安装或者最近更新排序进行管理"
这个不打算添加，存量扩展是没有安装时间和更新时间的，会造成这个功能可用性很差。

**Comment by JasonGrass** [comment]
“既然是管理面板了，是否可以增加一列版本信息显示呢”
可以在展开详情中添加，但是添加一列没有必要。扩展版本并不是一个平时使用需要关注的信息，而是一个关注度非常低频的信息，使用一列展示没有必要。

**Comment by JasonGrass** [comment]
0.5.4 版本处理了排序问题
版本号显示放在了展开的详情中

**Comment by y9287** [comment]
> 0.5.4 版本处理了排序问题 版本号显示放在了展开的详情中

为作者的更新热情点赞，经过这几天的更新，越来越好用了。
