### ISSUE TITLE
希望删除插件时支持设置不用弹框确认

### ISSUE THREAD

**Issue by y9287** [JasonGrass/auto-extension-manager#88]
删除时系统会弹框提示是否删除，所以完全不用弹框确认。

---

Extension Manager 0.5.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by JasonGrass** [comment]
0.5.5 版本已处理
