### ISSUE TITLE
Extension List with Links

### ISSUE THREAD

**Issue by gbsix** [JasonGrass/auto-extension-manager#90]
在“扩展管理”里面或者重新建一个标签：按分组显示列出全部已安装扩展和对应的商店链接。主要作用是批量整理（删除）和批量手动安装到其他浏览器，这个标签页面可以导出为HTML方便在其他浏览器打开链接，或者备份之用。
参考扩展：https://chrome.google.com/webstore/detail/extension-log/eiljhbjamiikjjldhnepillceohglbjh

**Comment by JasonGrass** [comment]
过于复杂了，如果是批量导出和导入，现在已经有了 

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/a9d67e36-4fb3-4924-b44f-1003dbd0c791)
