### ISSUE TITLE
能否增加一个折叠的按钮？

### ISSUE THREAD

**Issue by zhl111** [JasonGrass/auto-extension-manager#91]
如果分组很多，点开插件将会显示的非常长，但有些组是不需要展开看的，如果加上折叠选项，插件会显得更加干净利索
![image](https://github.com/JasonGrass/auto-extension-manager/assets/29135984/5c18eadd-69b4-40a0-92ab-7c19d61b612f)

**Comment by JasonGrass** [comment]
可以考虑，但近期没有时间处理了 
如果不需要在 popup 中看到某些扩展，可以将它们放在隐藏分组中

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/4e8842d5-65fd-4d59-b6d3-11ebb3dfefba)
