### ISSUE TITLE
不知道这个浏览器可不可以支持

### ISSUE THREAD

**Issue by xiaoyuhaoge** [JasonGrass/auto-extension-manager#92]
我使用的是ios Orion，这是此浏览器的API支持列表，可以安装扩展，但是好像显示有些兼容问题。
https://browser.kagi.com/WebExtensions-API-Support.html
我打开设置会白屏🤔

**Comment by JasonGrass** [comment]
现在只考虑主流桌面端浏览器，应该没有精力处理其它浏览器的扩展需求
