### ISSUE TITLE
建议增强隐藏扩展功能

### ISSUE THREAD

**Issue by StrollStars** [JasonGrass/auto-extension-manager#93]
目前扩展列表中，可以不显示固定分组中的扩展，建议有规则的扩展也能选择不显示，因为有的扩展用了规则就不需要手动开关了。
更进一步，支持对任意扩展或组不显示。

**Comment by JasonGrass** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/e1090a4f-038a-4f53-ab0e-3b072e025715)
