### ISSUE TITLE
规则：匹配才打开，目标扩展启用疑似不生效

### ISSUE THREAD

**Issue by SNANA51832** [JasonGrass/auto-extension-manager#94]

**Comment by JasonGrass** [comment]
反馈问题请提供具体的信息。每一项配置的截图，最好是能够直接导出配置文件，贴到这里。

**Comment by JasonGrass** [comment]
@SNANA51832  有具体的配置信息吗？

**Comment by SNANA51832** [comment]
> @SNANA51832 有具体的配置信息吗？
[ext_manager_config_20231114_100103.json](https://github.com/JasonGrass/auto-extension-manager/files/13343728/ext_manager_config_20231114_100103.json)

**Comment by SNANA51832** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/77220918/ff73210f-c7e8-411d-b888-5c1cad8e2b41)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/77220918/72cd9507-0f7c-4089-88e3-7cd6d3c3228a)
必须打开刷新，插件的美化界面才生效

**Comment by JasonGrass** [comment]
所以，看起来没啥问题？
对网页进行修改插件，一般都需要勾选 “启用扩展之后，刷新当前页面”，除非目标扩展自己做了特殊处理。这也是添加刷新这个功能的目的。

原因：目标扩展启用后，此时网页可能已经加载完成。目标扩展没有时机处理对网页的修改。

可以将动作设置成 自定义

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/cd7e1d9f-e54a-4e4c-9a18-f9b2d2f996db)

减少切换浏览器标签时，扩展的频繁启用与禁用

**Comment by SNANA51832** [comment]
我是按照之前二管家的逻辑认为的，他们是打开网页之前这种插件也会提前渲染好，你们这种处理现在也能接受吧
