### ISSUE TITLE
规则冲突不易发现，可能引起误解

### ISSUE THREAD

**Issue by kokojacket** [JasonGrass/auto-extension-manager#95]
添加的规则只有匹配后才关闭，经常只有部分扩展关闭，Tampermonkey一直在线。

**Comment by JasonGrass** [comment]
反馈问题请提供具体的配置信息

参考 #94

**Comment by kokojacket** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/74887370/e55e3d2f-3781-4b33-9d54-91b8033503f8)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/74887370/85a711cb-0efa-42af-b940-6fc74b8a5284)

**Comment by kokojacket** [comment]
设置的所有规则中只有翻译自动关闭，其余扩展全部失效

**Comment by JasonGrass** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/89a51f62-738e-4db0-8259-6e1a8b1a36b7)

我这里没有复现，你可以尝试如下调查方式

1 在 popup  中，手动关闭相关的扩展，看能不能正常关闭
2 检查 url 规则中是否有拼写错误
3 在扩展的设置页面，使用 F12 打开浏览器调试，检查控制台输出是否有错误信息

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/acd847c4-ab5d-4e8e-8c19-2cd9277795b8)

**Comment by JasonGrass** [comment]
找到问题了没？

**Comment by kokojacket** [comment]
没有，很神奇，popup中顶部显示禁用了翻译，然后尝试手动关闭篡改猴，可以正常关闭。说明1和2没有问题。F12调试我不太会看

**Comment by JasonGrass** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/9f07ce6f-1ea5-429a-9bc8-394db6a7a973)
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/dd9f2eb7-bed2-4094-b4ab-880c8f747287)

规则中配置了“禁用扩展后自动刷新当前页面”，可能导致上面扩展管理器的页面被刷新，看不到输出，这个需要注意一下，不要让扩展管理器的页面成为“当前页面”。

**Comment by kokojacket** [comment]
![image](https://github.com/JasonGrass/auto-extension-manager/assets/74887370/54a2250b-6287-4715-85fe-9d632775d2f0)

**Comment by JasonGrass** [comment]
不是任何一个页面的 控制台界面，你需要在扩展管理器的页面，打开 F12(检查页面)

![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/a5d669b0-b1c7-41a1-83ad-1884f98528c1)

**Comment by JasonGrass** [comment]
然后执行相关的操作，看控制台的输出

**Comment by kokojacket** [comment]
很神奇，确实只有翻译生效了
![image](https://github.com/JasonGrass/auto-extension-manager/assets/74887370/8d3c1a08-3ab4-4a1e-9f45-0b6bbfb83785)

**Comment by JasonGrass** [comment]
感觉你规则配置哪里有点问题

**Comment by JasonGrass** [comment]
可以把其它规则都先关闭了，只留需要测试的规则，再看看

**Comment by kokojacket** [comment]
确实，我尝试把规则改成bilibili.com后可以生效了，改为自己的域名就会出现问题。会不会因为我的域名需要带端口访问导致的。

**Comment by kokojacket** [comment]
因为需要域名+端口号导致我的通配符不正确？

**Comment by kokojacket** [comment]
并且添加两条规则之后会出现问题

**Comment by JasonGrass** [comment]
有点蒙圈，私聊？  jasontp@qq.com

**Comment by kokojacket** [comment]
好的我加您

**Comment by JasonGrass** [comment]
调查结论：
规则冲突，因为两个规则中包含相同的目标扩展，规则 1 中禁用的扩展，可能在规则 2 中被开启。最终状态取决于规则的执行顺序。

优化建议：
完成规则编辑之后，添加自动化的规则检查，看是否有可能冲突，如果有，则进行提示。
