### ISSUE TITLE
[疑问] 关于chrome 插件的一些问题

### ISSUE THREAD

**Issue by iamqiz** [JasonGrass/auto-extension-manager#96]
我在找方法使插件能pin和启动其它插件, 然后 发现了个可能有用的设置,
chrome://flags/ 里有个叫 "Extensions on chrome:// URLs" 的选项,  启用后还是不能让 content_scripts 访问 chrome://页面
content_scripts配置如下: 
```
  "content_scripts": [{
    "matches": ["<all_urls>","chrome://*/*","chrome://extensions/*"],
    "js": ["content.js"],
    "all_frames": true,
    "match_about_blank": true
  }],
```
请问你知道这个选项有啥用吗?

**Comment by JasonGrass** [comment]
这好像是两个独立的问题，

`使插件能pin和启动其它插件`  这个似乎没有 API 

"Extensions on chrome:// URLs" 看起来是让插件可以访问 chrome:// 开头的页面，至于为什么你这里配置了没有生效，这个我不是很了解  😂

**Comment by iamqiz** [comment]
@JasonGrass  我是想利用插件在后台打开其它插件的管理页面(chrome://extensions/?id=xxx),然后执行脚本点击"固定到工具栏" 从而实现pin😂
![Snipaste_环境返回_2023-11-17__23-16-38](https://github.com/JasonGrass/auto-extension-manager/assets/48077521/2a57d5e5-82e3-4039-a6d0-34f02fec5bd3)
结果,
document.querySelector() 抓不到元素

**Comment by JasonGrass** [comment]
一个有趣的思路，可能有些地方还是藏了点限制
