### ISSUE TITLE
建议：下拉菜单扩展图标增加版本号和隐藏开关

### ISSUE THREAD

**Issue by pipashu** [JasonGrass/auto-extension-manager#99]
工具栏的图标下拉菜单是否可以增加扩展的版本号以及隐藏开关，谢谢。

**Comment by JasonGrass** [comment]
没太看明白，具体是哪里的下拉菜单？
可以截图标记说明一下

**Comment by pipashu** [comment]
> 没太看明白，具体是哪里的下拉菜单？ 可以截图标记说明一下

点击工具栏上该扩展的图标不是下拉出所有扩展的菜单吗，每个扩展后面是开关，锁定，设置，删除和主页，能否在这加上版本号和隐藏开关。
<img width="413" alt="SCR-20231128-qlxs" src="https://github.com/JasonGrass/auto-extension-manager/assets/27265628/45084fc3-8b46-43b5-a295-912bf748ada8">

**Comment by JasonGrass** [comment]
## 固定分组的作用
![image](https://github.com/JasonGrass/auto-extension-manager/assets/10756994/f76f3969-df0f-4bb6-8f9b-1eace76defc1)

## 版本号
版本号就没必要显示了，好像没有什么场景，需要如此高频的知道扩展的版本号。99% 的情况下，都不需要知道扩展的版本号。
显示出来会显乱。

## 隐藏按钮
这个可以考虑，但是不想加那么多，看后面是不是加个配置。PS 现在配置项也感觉有点多，有点杂乱了。🤣
你现在可以在 分组管理 - 隐藏分组 中，添加需要隐藏的扩展。

**Comment by pipashu** [comment]
> ## 固定分组的作用
> ![image](https://private-user-images.githubusercontent.com/10756994/286228302-f76f3969-df0f-4bb6-8f9b-1eace76defc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzAxNDUsIm5iZiI6MTcwMTE2OTg0NSwicGF0aCI6Ii8xMDc1Njk5NC8yODYyMjgzMDItZjc2ZjM5NjktZGYwZi00YmI2LThmOWItMWVhY2U3NmRlZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZDBjMjI5OGFkMTQzNDQ4MTczN2QwMTQwOTMwZjAwY2M1OWM2NzM1MjhkNmQ4YmEzZDlkYzgwZDRjMmQ2MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8yDn2bO5_mWdpw8-IAZLXSYBOl6SK7ckV-4D4Ps_PWM)
> 
> ## 版本号
> 版本号就没必要显示了，好像没有什么场景，需要如此高频的知道扩展的版本号。99% 的情况下，都不需要知道扩展的版本号。 显示出来会显乱。
> 
> ## 隐藏按钮
> 这个可以考虑，但是不想加那么多，看后面是不是加个配置。PS 现在配置项也感觉有点多，有点杂乱了。🤣 你现在可以在 分组管理 - 隐藏分组 中，添加需要隐藏的扩展。

感谢回复，这个扩展非常棒，以前一直用的原版，后来发现有不良行为，改用了二管家，都不如你做的这个👍

**Comment by JasonGrass** [comment]
谢谢你的支持和喜爱~ ❤
